### ISSUE TITLE
Not sure this is a good example

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/angular-component-method-readme#2]
As far as I can tell, there is only a couple of small changes in these two large code blocks. Then the text below goes on to talk about scope, binding, and require. I think this example would be better if it included scope, binding, and require. 

@ipc103 @PeterBell

**Comment by PeterBell** [comment]
Sounds reasonable @aturkewi - want to take a stab next week at improving the example?

**Comment by aturkewi** [comment]
@PeterBell still think I'm a bit to green to be able to put forward a good example of directive -> component with all these change incorporated.

**Comment by PeterBell** [comment]
Gonna leave this for @ipc103 when he has the bandwidth then!
